version: '3.1'

services:
  # MySQL: https://hub.docker.com/_/mysql/ 
  single_db_instance:
    image: mysql:latest
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${MYSQL_NODE_HOSTNAME}
      restart_policy:
        condition: on-failure 
    ports:
      - "3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/lib/mysql"
      - "/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    secrets:
      - mysql_root_password

secrets:
   mysql_root_password:
     external: true




    
