version: '3.4'
services:
  fluentd:
    image: fluentd-efk
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      # fluent.conf 在宿主机上所在的目录的路径
      - "/fluentd/etc"
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${DEPLOY_NODE_HOSTNAME}
      restart_policy:
        condition: on-failure

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms300m -Xmx300m"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      # ES data 在宿主机上持久化数据目录的路径
      - "/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${DEPLOY_NODE_HOSTNAME}
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 600M
       
  kibana:
    image: kibana-efk
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    command: ["dockerize","-wait","tcp://elasticsearch:9200","-timeout","30s","kibana"]
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${DEPLOY_NODE_HOSTNAME}
      restart_policy:
        condition: on-failure
